---
- name: OpenVPN configuration
  hosts: ras_server
  become: yes
  tasks:
  - name: install applications
    apt:
      name:
        - easy-rsa
        - nano
        - traceroute
        - net-tools
        - openvpn
        - iperf3
      state: present
      update_cache: true
    #генерируем ключ и сертификаты
  - name: keys generation
    ansible.builtin.script: templates/certs_key_gen.sh
    args:
      creates: /etc/openvpn/playbook2.done
# Копируем сертификаты и ключ с сервера на клиент
  - name: Store ca cert to host
    ansible.builtin.fetch:
      src: /etc/openvpn/ca.crt
      dest: templates/ras_server/ca.crt
  - name: Store client cert to host
    ansible.builtin.fetch:
      src: /etc/openvpn/myclient.crt
      dest: templates/ras_server/myclient.crt
  - name: Store client key to host
    ansible.builtin.fetch:
      src: /etc/openvpn/myclient.key
      dest: templates/ras_server/myclient.key
  - name: Store ta.key to host
    ansible.builtin.fetch:
      src: /etc/openvpn/ta.key
      dest: templates/ras_server/ta.key
      
  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present
# копируем конфиг на сервер
  - name: copy server2.conf to server
    template:
      src: templates/ras_server.conf
      dest: /etc/openvpn/server2.conf
      owner: root
      group: root
      mode: 0640
#включаем/перезапускаем Open VPN службу
  - name: enable openvpn service
    service:
      name: openvpn@server2
      state: restarted
      enabled: true      