# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :"hw06-RPM" => {
              :box_name => "centos/stream8",
              :box_version => "20210210.0",
              :cpus => 4,
              :memory => 4096,
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
#    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
#      box.vm.provision "shell", path: "script.sh"
#      box.vm.provision 'shell', reboot: true
#      box.vm.provision "shell", path: "stage-2-check.sh"
    end
  end
end