FROM nginx
WORKDIR ./html-data
COPY ./html-data/index.html /usr/share/nginx/html && ./html-data/index2.html /usr/share/nginx/html
EXPOSE 80
EXPOSE 3000
VOLUME /var/log/nginx
VOLUME /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]