---
- hosts: master
  become: yes
  tasks:
  - name: copy master dump from master
    ansible.builtin.fetch:
      src: /vagrant/master.sql
      dest: conf/master.sql
- hosts: slave
  become: yes
  tasks:
  - name: Install repo Percona
    yum:
      name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      state: present
  - name: install Percona and tools
    yum:
      name:
        - Percona-Server-server-57
        - nano
      state: present
  - name: copy dump to slave
    copy:
      src: conf/master.sql/master/vagrant/master.sql
      dest: /vagrant/master.sql
  - name: copy configs
    ansible.builtin.copy:
      src: conf/conf.d/
      dest: /etc/my.cnf.d