# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :"les10-11-bash" => {
#              :box_name => "centos/stream8",
              :box_name => "centos/7",
#              :box_version => "20210210.0",
              :box_version => "2004.01",
              :cpus => 2,
              :memory => 2048,
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
#    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
#      box.vm.provision "shell", path: "script.sh"
      box.vm.provision "shell", inline: <<-SHELL
        yum install -y mailutils
        echo "0 * * * * /vagrant/script.sh" | crontab #каждый час
        SHELL
      
    end
  end
end