# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :ClientVM => {
    :box_name => "centos/stream8",
    :box_version => "20210210.0",
    :ip_addr => '192.168.56.101',
    :cpus => 1,
    :memory => 2048
  },
#  :ClientVM => {
#    :box_name => "ubuntu/focal64",
#    :box_version => "ubuntu/focal64",
#    :ip_addr => '192.168.56.102',
#    :cpus => 2,
#    :memory => 2048
#  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      config.vm.synced_folder ".", "/vagrant", disabled: true

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
            vb.memory = boxconfig[:memory]
            vb.cpus = boxconfig[:cpus]
          end
          box.vm.provision "shell", inline: <<-SHELL
#            apt install python3 -y
            yum install -y python3
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL
          #box.vm.provision "shell", path: "server_script.sh"
        end
    end
end     