# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
    :box_name => "centos/stream8",
    :box_version => "20210210.0",
    :ip_addr => '192.168.56.101',
    :cpus => 2,
    :memory => 2048,
    :disks => {
      :sata1 => {
        :dfile => 'sata1.vdi',
        :size => 100,
        :port => 1
      },
      :sata2 => {
        :dfile => 'sata2.vdi',
        :size => 150,
        :port => 2
      },
      :sata3 => {
        :dfile => 'sata3.vdi',
        :size => 150,
        :port => 3
      },
      :sata4 => {
        :dfile => 'sata4.vdi',
        :size => 150,
        :port => 4
      },
      :sata5 => {
        :dfile => 'sata5.vdi',
        :size => 150,
        :port => 5
    }
    }
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      config.vm.synced_folder ".", "/vagrant", disabled: true

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.memory = boxconfig[:memory]
            vb.cpus = boxconfig[:cpus]
            vb.customize ["storagectl", :id, "--name", "SATA controller", "--add", "sata" ] #create SATA controller
            boxconfig[:disks].each do |dname, dconf|
              unless File.exist?(dconf[:dfile])
                vb.customize ['createmedium', '--filename', dconf[:dfile], '--size', dconf[:size], '--variant', 'Standard'] #create disks (why there is not "createmedium"?)
                vb.customize ['storageattach', :id,  '--storagectl', 'SATA controller', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]] #attach Disks to SATA controller
              end  
            end
          end
#          box.vm.provision "shell", inline: <<-SHELL
#          mkdir -p ~root/.ssh
#          cp ~vagrant/.ssh/auth* ~root/.ssh
#          yum install -y mdadm smartmontools hdparm gdisk lvm2
#          SHELL
          box.vm.provision "shell", path: "stage-1-mdadm.sh"
        end
    end
end