version: "3.1"

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 88:80
    environment:
      - PMA_HOST=192.168.56.55

  grafana:
    image: grafana/grafana:8.5.3-ubuntu
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana

  prometheus:
    image: prom/prometheus:v2.36.0
    ports:
      - "9090:9090"
    volumes:
      - prom-data:/prometheus
      - prom-configs:/etc/prometheus
  
  dashboard:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - TZ=Europe/Moscow
      - PGID=1001
      - PUID=1010
    volumes:
      - heimdall-configs:/opt/heimdail/config
    ports:
      - "80:80"
      - "443:443"
    restart: always    

  node-exporter:
    image: prom/node-exporter:v1.3.1
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
  # на странице образа в docker hub написано, какие можно задать переменные контейнеру https://hub.docker.com/_/wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: 192.168.56.55
      WORDPRESS_DB_NAME: wp # лучше использовать переменную или хэш
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: Otus2023!
    volumes:
      - ./wordpress:/var/www/html # сохраняем приложение на хост машине
  
volumes:
  grafana-data:
  grafana-configs:
  prom-data:
  prom-configs:
  heimdall-configs: 